version: 1

disable_existing_loggers: False

formatters:
  simple:
    format: '%(asctime)s %(levelname)s %(message)s'
  upgrade:
    format: "%(asctime)s -Loc %(filename)s -Pid %(process)d -%(name)s -%(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

# 按照文件大小分割
  info_file_handler:
    class: cloghandler.ConcurrentRotatingFileHandler
    level: INFO
    formatter: simple
    filename: logs/info_rotating.log
    maxBytes: 1024 # 10MB
    backupCount: 20 #most 20 extensions
    encoding: utf8
# 按照文件大小分割
  error_file_handler:
    class: cloghandler.ConcurrentRotatingFileHandler
    level: ERROR
    formatter: upgrade
    filename: logs/errors_rotating.log
    maxBytes: 1024 # 10MB
    backupCount: 20
    encoding: utf8
# 按照时间分割
#  info_file_handler:
#    class: logging.handlers.TimedRotatingFileHandler
#    level: DEBUG
#    formatter: simple
#    filename: logs/info_time.log  #这个路径根据自己的日志存放路径填写
#    interval: 1
#    backupCount: 2 #most 2 extensions
#    encoding: utf8
#    when: H #这里是按小时生成

loggers:
  server:
    level: DEBUG #允许打印DEBUG及以上log
    handlers: [ info_file_handler ]
    propagate: true #设为false则禁止将日志消息传递给父级记录器的处理程序中

root:
  level: INFO
  handlers: [ info_file_handler,error_file_handler ]

